// Source-of-truth list of roads. Geometry is fetched from OpenStreetMap by
// scripts/fetch-roads.mjs; nothing here is copied from another map.
//
// `match` is the OSM selector. Prefer `ref` for state routes (the name changes
// every few miles) and `name` for everything else. `bbox` is [s, w, n, e] and
// exists to keep same-named roads elsewhere in California out of the results.

export const ROADS = [
  // ── Peninsula & Santa Cruz Mountains ──────────────────────────────────────
  {
    id: 'page-mill',
    name: 'Page Mill Road',
    region: 'Peninsula',
    blurb: 'Tight, technical climb from Palo Alto up to Skyline.',
    match: { name: 'Page Mill Road' },
    bbox: [37.28, -122.25, 37.42, -122.09],
  },
  {
    id: 'alpine',
    name: 'Alpine Road',
    region: 'Peninsula',
    blurb: 'Narrow and shaded, running west off Skyline toward Portola Valley.',
    match: { name: 'Alpine Road' },
    bbox: [37.28, -122.30, 37.42, -122.14],
  },
  {
    id: 'old-la-honda',
    name: 'Old La Honda Road',
    region: 'Peninsula',
    blurb: 'One lane, no centre line, relentless switchbacks.',
    match: { name: 'Old La Honda Road' },
    bbox: [37.28, -122.32, 37.42, -122.14],
  },
  {
    id: 'hwy-84',
    name: 'Highway 84 — La Honda',
    region: 'Peninsula',
    blurb: 'Fast, flowing and wide by local standards. Woodside to the coast.',
    match: { ref: 'CA 84' },
    searchNames: ['La Honda Road', 'Woodside Road'],
    bbox: [37.22, -122.40, 37.50, -122.17],
  },
  {
    id: 'kings-mountain',
    name: 'Kings Mountain Road',
    region: 'Peninsula',
    blurb: 'Redwood-lined climb out of Woodside to Skyline.',
    match: { name: 'Kings Mountain Road' },
    bbox: [37.38, -122.36, 37.52, -122.21],
  },
  {
    id: 'tunitas-creek',
    name: 'Tunitas Creek Road',
    region: 'Coast',
    blurb: 'Skyline down to Highway 1. Damp, dark and usually deserted.',
    match: { name: 'Tunitas Creek Road' },
    bbox: [37.30, -122.44, 37.44, -122.20],
  },
  {
    id: 'skyline',
    name: 'Skyline Boulevard (35)',
    region: 'Peninsula',
    blurb: 'The ridge road. Long sweepers along the spine of the peninsula.',
    match: { ref: 'CA 35' },
    searchNames: ['Skyline Boulevard'],
    bbox: [37.15, -122.38, 37.55, -122.08],
  },
  {
    id: 'hwy-9-saratoga',
    name: 'Highway 9 — Saratoga',
    region: 'Santa Cruz Mtns',
    blurb: 'Congress Springs. Steady rhythm from Saratoga up to the ridge.',
    match: { ref: 'CA 9' },
    searchNames: ['Congress Springs Road', 'Big Basin Way'],
    bbox: [37.22, -122.16, 37.32, -122.01],
  },
  {
    id: 'hwy-9-redwood',
    name: 'Highway 9 — Redwoods',
    region: 'Santa Cruz Mtns',
    blurb: 'The southern run through Boulder Creek and Felton.',
    match: { ref: 'CA 9' },
    searchNames: ['Highway 9', 'Big Basin Way'],
    bbox: [37.03, -122.16, 37.22, -122.00],
  },
  {
    id: 'bear-creek',
    name: 'Bear Creek Road',
    region: 'Santa Cruz Mtns',
    blurb: 'Connects 17 to Highway 9 the long, interesting way.',
    match: { name: 'Bear Creek Road' },
    bbox: [37.08, -122.12, 37.26, -121.94],
  },
  {
    id: 'stevens-canyon',
    name: 'Stevens Canyon Road',
    region: 'Peninsula',
    blurb: 'Reservoir run that narrows to a single lane at the top.',
    match: { name: 'Stevens Canyon Road' },
    bbox: [37.24, -122.16, 37.36, -122.04],
  },
  {
    id: 'mt-eden',
    name: 'Mount Eden Road',
    region: 'Santa Cruz Mtns',
    blurb: 'Short, blind and famously off-camber.',
    match: { name: 'Mount Eden Road' },
    bbox: [37.23, -122.14, 37.33, -122.02],
  },

  // ── South & East Bay ──────────────────────────────────────────────────────
  {
    id: 'mt-hamilton',
    name: 'Mount Hamilton Road',
    region: 'Diablo Range',
    blurb: 'Nineteen miles of switchbacks to the observatory at 4,200 ft.',
    match: { name: 'Mount Hamilton Road' },
    bbox: [37.26, -121.82, 37.44, -121.58],
  },
  {
    id: 'mines',
    name: 'Mines Road',
    region: 'Diablo Range',
    blurb: 'Remote, empty and very long. No services, no phone signal.',
    match: { name: 'Mines Road' },
    bbox: [37.33, -121.68, 37.74, -121.44],
  },
  {
    id: 'calaveras',
    name: 'Calaveras Road',
    region: 'East Bay',
    blurb: 'Reservoir sweepers between Milpitas and Sunol.',
    match: { name: 'Calaveras Road' },
    bbox: [37.38, -121.93, 37.64, -121.72],
  },
  {
    id: 'sierra',
    name: 'Sierra Road',
    region: 'East Bay',
    blurb: 'Brutally steep wall climbing straight out of San Jose.',
    match: { name: 'Sierra Road' },
    bbox: [37.36, -121.88, 37.50, -121.68],
  },
  {
    id: 'san-antonio-valley',
    name: 'San Antonio Valley Road',
    region: 'Diablo Range',
    blurb: 'The far side of Mount Hamilton. Wide open and fast.',
    match: { name: 'San Antonio Valley Road' },
    bbox: [37.26, -121.62, 37.48, -121.36],
  },
  {
    id: 'del-puerto-canyon',
    name: 'Del Puerto Canyon Road',
    region: 'Diablo Range',
    blurb: 'Drops east out of the range into the Central Valley heat.',
    match: { name: 'Del Puerto Canyon Road' },
    bbox: [37.30, -121.48, 37.58, -121.10],
  },

  // ── East Bay Hills ────────────────────────────────────────────────────────
  {
    id: 'pinehurst',
    name: 'Pinehurst Road',
    region: 'East Bay',
    blurb: 'Tight, mossy and narrow through Canyon.',
    match: { name: 'Pinehurst Road' },
    bbox: [37.78, -122.24, 37.92, -122.08],
  },
  {
    id: 'redwood',
    name: 'Redwood Road',
    region: 'East Bay',
    blurb: 'Long climb out of Castro Valley into the Oakland hills.',
    match: { name: 'Redwood Road' },
    bbox: [37.72, -122.22, 37.90, -122.02],
  },
  {
    id: 'palomares',
    name: 'Palomares Road',
    region: 'East Bay',
    blurb: 'Quiet canyon linking Castro Valley to Niles. Often overlooked.',
    match: { name: 'Palomares Road' },
    bbox: [37.58, -122.03, 37.76, -121.86],
  },
  {
    id: 'grizzly-peak',
    name: 'Grizzly Peak Boulevard',
    region: 'East Bay',
    blurb: 'Ridge road above Berkeley with the whole bay on one side.',
    match: { name: 'Grizzly Peak Boulevard' },
    bbox: [37.83, -122.30, 37.96, -122.15],
  },
  {
    id: 'wildcat-canyon',
    name: 'Wildcat Canyon Road',
    region: 'East Bay',
    blurb: 'Fast, open and grassy through Tilden.',
    match: { name: 'Wildcat Canyon Road' },
    bbox: [37.86, -122.32, 38.00, -122.16],
  },
];
